### ISSUE TITLE
 HTML/CSS:  Initial rung dropdown size is weaksauce

### ISSUE THREAD

**Issue by karldreher** [karldreher/5BX#2]
I've known it for some time - the dropdown is barely visible in the interface.  

I've come to understand that this is a CSS limitation which can be overcome by writing some Jquery to wrap the input, but for me this didn't work (possibly due to a nesting issue or possibly when the dropdown is created, see below).  

I don't understand this well enough to fix and I'm looking for help from anyone who might be able to - I'm willing to consider other inputs (spinners or plain text entry) provided there is adequate input validation to avoid using too high of a number (should not go out of bounds of the array, currently 1-48).  

The benefit of the dropdown is that it's dynamically created based on the array (and has builtin input validation), in which case fixing this might incur a significant re-architecture, or at least a redesign of that dynamic creation.

**Comment by tsriram** [comment]
How about having it as a input box which accepts only a number in the range 1-48?

**Comment by tsriram** [comment]
@karldreher this looks like a decent option - https://select2.github.io/

Have submitted a PR with this change. See if it works for you.

**Comment by karldreher** [comment]
@tsriram Hi, thanks for the pull request.  I'm looking at this but haven't finished testing.  At first glance, this didn't appear to fix the issue.  Although it's a more modern look which does look better, the issue is mostly with the size of the select box itself.  I might lean toward your earlier suggestion of an input box, I think that is probably a simpler way to go.

**Comment by tsriram** [comment]
@karldreher updated it with an input box.

**Comment by karldreher** [comment]
Fixed in #4
